### PR TITLE
Spotbit integration & spotbit server/currency/exchange selection

### PR DESCRIPTION
**Pull request by gg2001**
- Localized the currency symbol (shows ¥ for CNY, £ for GBP, $ for USD, etc)
- Allows a user to add spotbit servers of their choice
- Better error handling (such as when spotbit is offline or if spotbit isn't functioning properly)
- Sets currency automatically based on users locale
- Allows users to select the currency (defaults to your locales currency, if it isn't available it defaults to USD) and exchange (defaults to coinbase)

Simulator Screen Shot - iPhone 11 - 2020-08-16 at 08 34 18
Simulator Screen Shot - iPhone 11 - 2020-08-16 at 08 33 05
Simulator Screen Shot - iPhone 11 - 2020-08-16 at 08 32 49
Simulator Screen Shot - iPhone 11 - 2020-08-16 at 08 32 53

### CODE REVIEW

**Comment by Fonta1n3** [comment]
Hey @gg2001 , I have been testing Spotbit quite heavily and am running into serious reliability issues. Today I have unfortunately made the decision to revert back to using the blockchain.info api over Tor in Fully Noded as Spotbit has been giving me a lot of issues (which is fair enough as it is brand new), I jumped the gun a bit and am afraid this PR is also jumping the gun. Nothing wrong with your code but I am not sure Spotbit is quite ready yet.

**Comment by Fonta1n3** [comment]
@gg2001 Just did a few tests on macOS and iOS simulator. 

Looks like there is an issue with UIPickerView not showing on macOS:

Screen Shot 2020-09-11 at 9 51 32 AM

Screen Shot 2020-09-11 at 9 52 03 AM

On iOS after changing the currency to `IDR` and the exchange to `dsx` the `$` symbol remains:

Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-11 at 10 02 39

Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-11 at 10 02 33

After receiving some `tbtc` I get `no price data` error:

Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-11 at 10 10 30

Simulator Screen Shot - iPhone 11 Pro Max - 2020-09-11 at 10 10 03

We should probably only support the most popular exchanges instead of what seems to be all of them.

**Comment by Fonta1n3** [comment]
+1 LGTM, when balance is 0 it still hangs on the previous fiat symbol but other then that looks great. @ChristopherA I think this can be merged now.

**Comment by ggelango** [comment]
Ah yes I'll fix it that bug. I'm also adding an Average selection option in the settings which will be accessible for USD, GBP, EUR and JPY. All this will do is call /now/[currency] instead of /now/[currency]/[exchange]. I will be pushing tmrw morning, so by around 6PM Friday pacific time, it can be merged.

**Comment by Fonta1n3** [comment]
@ChristopherA  is there any reason this isn’t getting merged? I have more committs to submit but don’t want to leap frog Gauthams work.

**Comment by ChristopherA** [comment]
I'm getting 3 warnings for /FullyNoded-2/ directories not found, and one build error:

```
GordianWallet Group
Warning Group
Directory not found for option '-L/Users/admin/projects/github/BlockchainCommons/FullyNoded-2/XCode/Pods/LibWally/CLibWally/libwally-core/src/.libs'
Directory not found for option '-F/Users/admin/projects/github/BlockchainCommons/FullyNoded-2/XCode/Carthage/Build/iOS'
Directory not found for option '-F/Users/admin/projects/github/BlockchainCommons/FullyNoded-2/XCode/Carthage/Build/Mac'
Uncategorized Group
Command PhaseScriptExecution failed with a nonzero exit code
```

**Review by ChristopherA — APPROVED** [review]
Tested ACK. Built on macOS Catalina (10.15.6), using Xcode 11.7, testing Spotbit but no regression testing.

**Comment by ChristopherA** [comment]
Should be done in next PR

* set debug modes so I don't have to log in with Apple (and make notes for full regression to turn them back on).
* Update install docs. You also don't need the extra `cd`, just `open Xcode/GordianWallet.xcodeproj`
* Spotbit price pair should be visible in Out pane. Probably also need a (i) with what that price currently is based on.

**Pull request merged**
