### PR TITLE
LogInViewController update

### PR DESCRIPTION
**Pull request by brett-doffing**
Moved UIViewController extension to Utilities.
Instantiated LogInViewController directly in SceneDelegate.
Setup use of auto layout in LogInViewController.
Moved additional protocols to an extension for separation.

### CODE REVIEW

**Comment by brett-doffing** [comment]
More looking to see if there is anything else to do or add here, while simply giving an example of how I would implement this.

**Review by Fonta1n3 — APPROVED** [review]
LGTM +1

**Comment by ChristopherA** [comment]
This PR is still marked as a "work in progress". Let me know when it is ready for review after @Fonta1n3 builds and tests it by having either @doffing81 or @Fonta1n3 click on "ready for review" button.

**Comment by Fonta1n3** [comment]
@doffing81 Please let me know if you want me to merge this or if it is still a WIP?

**Comment by brett-doffing** [comment]
I was looking to see if anything else should be done. If there isn't anything more, then it should be ok to merge.

**Comment by Fonta1n3** [comment]
There are conflicts so looks like you need to rebase before it can be merged, my previous PR had made some changes to the LogInViewController which looks to be the culprit.

**Comment by Fonta1n3** [comment]
@doffing81 Just FYI I will shoot you an email with regards to to do items, there are many ;) Thank you!

**Comment by Fonta1n3** [comment]
NIT:

Can we keep the existing frame
`logInButton.frame = CGRect(x: 32, y: 100, width: view.frame.width - 64, height: 80)`

and the existing text styling:
`description.font = .systemFont(ofSize: 16, weight: .light)`

and the existing text description:
`description.text = "Blockchain Commons, LLC and FullyNoded 2 do not use or save your Apple ID data in anyway, it is used solely for 2FA (two-factor authentication) purposes only."`

**Comment by brett-doffing** [comment]
Keep the existing frame as in not use constraints? I can definitely keep/change whatever sizing, styling, and position. This then begs what I should do with the sizing and positioning of the label, other than the text itself? 

You don't find it weird to say that you don't use the Apple ID, while using it, and then saying that you use it?

**Comment by Fonta1n3** [comment]
You can programmatically use the data, we do not. Please keep all existing frames as they are.

**Comment by Fonta1n3** [comment]
To clarify when I built the PR the button moved significantly down the screen. I guess I should say keep the existing position, please.

**Comment by brett-doffing** [comment]
I am just going to close this PR as it was originally meant to show a different way of doing things, while possibly being added to, but it doesn’t look like anything is to be added, the methodology has been shown, and everything is to be kept as it was before the PR, so it is nothing more than redundant.

**Pull request closed without merging**
