### PR TITLE
UR crypto-psbt support

### LINKED ISSUE #96: Cannot Import Watch-Only from Specter-Desktop
Steps:
1. Create multisig wallet on Specter-Desktop:
2. Open Gordian iOS and click on `Accounts` tab.
3. Click on QR icon in upper left and scan `Export Wallet` QR code from Specter-Desktop (http://127.0.0.1:25441/wallets/WALLETNAMEHERE/settings/)

Screen Shot 2020-10-08 at 10 48 54 AM

```{ "label": "Cobo Seedpicker Generated", "blockheight": 1859308, "descriptor": "wsh(sortedmulti(1,[c7d0648a\/48h\/1h\/0h\/2h]tpubDEpefcgzY6ZyEV2uF4xcW2z8bZ3DNeWx9h2BcwcX973BHrmkQxJhpAXoSWZeHkmkiTtnUjfERsTDTVCcifW6po3PFR1JRjUUTJHvPpDqJhr\/0\/*,[f7d04090\/48h\/1h\/0h\/2h]tpubDF7FTuPECTePubPXNK73TYCzV3nRWaJnRwTXD28kh6Fz4LcaRzWwNtX153J7WeJFcQB2T6k9THd424Kmjs8Ps1FC1Xb81TXTxxbGZrLqQNp\/0\/*))#sa6r7elh" }```

4. Hangs on "processing..." forever (restarting the app doesn't help):
83B8C73D-EC46-4599-A13F-7D2B5E830E52_1_105_c

My use-case is ultimately that I want to see if I can use Gordian as a cosigner in a multisig wallet, but for now I'm seeing if it can just do receive address validation (no private keys).

### PR DESCRIPTION
**Pull request by Fonta1n3**
Fixes #96  #95 #92 #91

### CODE REVIEW

**Review by ChristopherA — CHANGES_REQUESTED** [review]
Tested NACK: Built on macOS Catalina (10.15.6) (inside VMware 11.5.6) using Xcode 11.7.

Built with no errors on freshly installed VM snapshot post-Xcode install, for target iPhone SE Simulator, using the following:

```
brew install carthage
git clone git@github.com:BlockchainCommons/GordianWallet-iOS.git
cd GordianWallet-iOS
gh pr checkout 97
open XCode/GordianWallet.xcodeproj
```
A number of problems:

When wallet starts up, it shows me "Scan QR Code", however, does not ask me the normal startup scripts. As the simulator in this VM has never been run before, this does not make sense, as it should go through "open wallet the first time" script first.

Second, I am unable to select our testing node. I presume this maybe because this build is mainnet? We should not have mainnet builds to master yet. If this build is not mainnet there is some other problem. In any case, I can't test.

Lastly, on this "Scan a QR Code" screen I can't click on the X to close the scan to see what is going on, or try killing the settings, and such. 

So totally stuck on testing this PR.

**Comment by Fonta1n3** [comment]
> Tested NACK: Built on macOS Catalina (10.15.6) (inside VMware 11.5.6) using Xcode 11.7.
> 
> 
> 
> Built with no errors on freshly installed VM snapshot post-Xcode install, for target iPhone SE Simulator, using the following:
> 
> 
> 
> ```
> 
> brew install carthage
> 
> git clone git@github.com:BlockchainCommons/GordianWallet-iOS.git
> 
> cd GordianWallet-iOS
> 
> gh pr checkout 97
> 
> open XCode/GordianWallet.xcodeproj
> 
> ```
> 
> A number of problems:
> 
> 
> 
> When wallet starts up, it shows me "Scan QR Code", however, does not ask me the normal startup scripts. As the simulator in this VM has never been run before, this does not make sense, as it should go through "open wallet the first time" script first.
> 
> 
> 
> Second, I am unable to select our testing node. I presume this maybe because this build is mainnet? We should not have mainnet builds to master yet. If this build is not mainnet there is some other problem. In any case, I can't test.
> 
> 
> 
> Lastly, on this "Scan a QR Code" screen I can't click on the X to close the scan to see what is going on, or try killing the settings, and such. 
> 
> 
> 
> So totally stuck on testing this PR.
> 
> 
> 
> 
> 
> 

Not mainnet.

Not sure what scripts your talking about.

Will test on a fresh install to see if I can figure out what you mean.

**Comment by ChristopherA** [comment]
Scripts=All the initial startup text screens you have to go through. Somehow in this version they are gone and first thing you see is Scan window which can’t be closed with x box

**Comment by Fonta1n3** [comment]
> Scripts=All the initial startup text screens you have to go through. Somehow in this version they are gone and first thing you see is Scan window which can’t be closed with x box

ah OK, will send an update address all these issues shortly.

**Comment by Fonta1n3** [comment]
@ChristopherA Your onboarding issues and scanning issues should be resolved now as well as #98 #101 #99 and a few other things I noticed which are itemized in the commit messages.

Please do try again.

**Review by ChristopherA — APPROVED** [review]
Tested ACK: Built on macOS Catalina (10.15.6) (inside VMware 11.5.6) using Xcode 11.7.

Built from previous pull, with no errors on freshly installed VM snapshot post-Xcode install, for target iPhone SE Simulator, using the following:

```
git pull
git clean --ffdx
rm -rf ~/Library/Developer/Xcode/DerivedData/*
open Xcode/GordianWallet.xcodeproj
```

Tested:
* [x] Add default shared testate node
* [x]  Creation of default hot wallet
* [x] See new LifeHash
* [x] Copy words to clipboard for backup
* [x] Create invoice
* [x] Send testnet coins to wallet
* [x] see balance change
* [x] see a spotbit "price"
* [x] see confirmed change
* [x] sweep funds to TestFlight 0.1.90 warm wallet. Had problems there, see #102, but ultimately did receive funds. We need to resolve this issue but not blocking this PR to master.

I consider this bare minimal testing. No other regression testing was done.

(NOTE: that there are 3 build warnings about "result of call to 'remove(key:)' is unused" — please investigate — anything about keys worries me).

**Pull request merged**
